name: text_sns
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_flavor: ^3.1.3
  flutter_flavorizr: ^2.2.3
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  fluttertoast: ^8.1.2
  firebase_auth: ^5.0.0
  firebase_remote_config: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
      flavorDimensions: "flavor-type"
  flavors:
    dev:
      app:
        name: "Text SNS Dev"
      android:
        applicationId: "com.firebaseapp.text_sns_dev_1c0a6"
      ios:
        bundleId: "com.firebaseapp.textSnsDev1c0a6"
    prod:
      app:
        name: "Text SNS"
      android:
        applicationId: "com.firebaseapp.text_sns_prod_f5147"
      ios:
        bundleId: "com.firebaseapp.textSnsProdF5147"
